import type { ComponentType } from 'react'

export type HeroLoader = () => Promise<{ default: ComponentType<any> }>

export const heroLoaders: Record<string, HeroLoader> = {
  1: () => import('@/heros/PageHero/hero1').then((m) => ({ default: m.Hero1 })),
  2: () => import('@/heros/PageHero/hero2').then((m) => ({ default: m.Hero2 })),
  3: () => import('@/heros/PageHero/hero3').then((m) => ({ default: m.Hero3 })),
  4: () => import('@/heros/PageHero/hero4').then((m) => ({ default: m.Hero4 })),
  5: () => import('@/heros/PageHero/hero5').then((m) => ({ default: m.Hero5 })),
  6: () => import('@/heros/PageHero/hero6').then((m) => ({ default: m.Hero6 })),
  7: () => import('@/heros/PageHero/hero7').then((m) => ({ default: m.Hero7 })),
  8: () => import('@/heros/PageHero/hero8').then((m) => ({ default: m.Hero8 })),
  9: () => import('@/heros/PageHero/hero9'),
  10: () => import('@/heros/PageHero/hero10'),
  11: () => import('@/heros/PageHero/hero11'),
  12: () => import('@/heros/PageHero/hero12'),
  13: () => import('@/heros/PageHero/hero13'),
  14: () => import('@/heros/PageHero/hero14'),
  15: () => import('@/heros/PageHero/hero15'),
  16: () => import('@/heros/PageHero/hero16'),
  18: () => import('@/heros/PageHero/hero18'),
  20: () => import('@/heros/PageHero/hero20'),
  21: () => import('@/heros/PageHero/hero21'),
  24: () => import('@/heros/PageHero/hero24'),
  25: () => import('@/heros/PageHero/hero25'),
  26: () => import('@/heros/PageHero/hero26'),
  27: () => import('@/heros/PageHero/hero27'),
  28: () => import('@/heros/PageHero/hero28'),
  29: () => import('@/heros/PageHero/hero29'),
  30: () => import('@/heros/PageHero/hero30'),
  31: () => import('@/heros/PageHero/hero31').then((m) => ({ default: m.Hero31 })),
  32: () => import('@/heros/PageHero/hero32'),
  33: () => import('@/heros/PageHero/hero33'),
  34: () => import('@/heros/PageHero/hero34'),
  35: () => import('@/heros/PageHero/hero35'),
  36: () => import('@/heros/PageHero/hero36'),
  37: () => import('@/heros/PageHero/hero37'),
  38: () => import('@/heros/PageHero/hero38'),
  39: () => import('@/heros/PageHero/hero39'),
  40: () => import('@/heros/PageHero/hero40'),
  45: () => import('@/heros/PageHero/hero45'),
  50: () => import('@/heros/PageHero/hero50'),
  51: () => import('@/heros/PageHero/hero51'),
  53: () => import('@/heros/PageHero/hero53'),
  55: () => import('@/heros/PageHero/hero55'),
  57: () => import('@/heros/PageHero/hero57'),
  101: () => import('@/heros/PageHero/hero101'),
  112: () => import('@/heros/PageHero/hero112'),
  195: () => import('@/heros/PageHero/hero195'),
  220: () => import('@/heros/PageHero/hero220').then((m) => ({ default: m.Hero220 })),
  214: () => import('@/heros/PageHero/hero214').then((m) => ({ default: m.Hero214 })),
  219: () => import('@/heros/PageHero/hero219').then((m) => ({ default: m.Hero219 })),
  'ORISA_PAGE_01': () =>
    import('@/heros/PageHero/heroOrisaPage01').then((m) => ({ default: m.HeroOrisaPage01 })),
  'ORISA_MARKETING_01': () =>
    import('@/heros/PageHero/heroOrisaMarketing01').then((m) => ({
      default: m.HeroOrisaMarketing01,
    })),
  'ORISA_CREATIVE_01': () =>
    import('@/heros/PageHero/heroOrisaCreative01').then((m) => ({ default: m.HeroOrisaCreative01 })),
  'CORP_01': () => import('@/heros/PageHero/heroCorp01').then((m) => ({ default: m.HeroCorp01 })),
  'FOOD_01': () => import('@/heros/PageHero/heroFood01').then((m) => ({ default: m.HeroFood01 })),
}
