export type OrisaLayoutTemplate =
  | 'creative'
  | 'marketing'
  | 'about'
  | 'contact'
  | 'portfolio'
  | 'minimal'

export interface OrisaBundleDefinition {
  /** Asset bucket key under public/seed/orisa/{key}/ */
  key: string
  html: string
  title: string
  bundleSlug: string
  pageSlug: string
  description: string
  template: OrisaLayoutTemplate
  tagline: string
  headline: string
  /** Seeded by a dedicated script (skip generic seeder) */
  dedicated?: boolean
}

export const ORISA_BUNDLE_REGISTRY: OrisaBundleDefinition[] = [
  {
    key: 'creative',
    html: 'index.html',
    title: 'Orisa — Creative Agency',
    bundleSlug: 'orisa-creative-agency',
    pageSlug: 'home',
    description: 'Full Orisa Creative Agency demo from index.html',
    template: 'creative',
    tagline: 'B2B Marketing Agency',
    headline: 'Designing with imagination, driven by purpose.',
    dedicated: true,
  },
  {
    key: 'marketing',
    html: 'index-3.html',
    title: 'Orisa — Marketing Agency',
    bundleSlug: 'orisa-marketing-agency',
    pageSlug: 'orisa-marketing',
    description: 'Full Orisa Marketing Agency demo from index-3.html',
    template: 'marketing',
    tagline: 'Performance Marketing Agency',
    headline: 'Marketing That Delivers Real Value',
    dedicated: true,
  },
  {
    key: 'about',
    html: 'about-1.html',
    title: 'Orisa — About 01',
    bundleSlug: 'orisa-about-01',
    pageSlug: 'about',
    description: 'Orisa About 01 inner page',
    template: 'about',
    tagline: 'About Us',
    headline: 'We are a creative digital agency shaping meaningful experiences',
    dedicated: true,
  },
  {
    key: 'contact',
    html: 'contact-1.html',
    title: 'Orisa — Contact 01',
    bundleSlug: 'orisa-contact-01',
    pageSlug: 'contact',
    description: 'Orisa Contact 01 inner page',
    template: 'contact',
    tagline: 'Contact Us',
    headline: 'Get in touch',
    dedicated: true,
  },
  {
    key: 'digital',
    html: 'index-2.html',
    title: 'Orisa — Digital Agency',
    bundleSlug: 'orisa-digital-agency',
    pageSlug: 'orisa-digital-agency',
    description: 'Orisa Digital Agency homepage demo (index-2.html)',
    template: 'creative',
    tagline: 'Digital Agency',
    headline: 'We craft digital experiences that move brands forward',
  },
  {
    key: 'home-4',
    html: 'index-4.html',
    title: 'Orisa — AI & Tech Agency',
    bundleSlug: 'orisa-ai-tech-agency',
    pageSlug: 'orisa-ai-tech-agency',
    description: 'Orisa AI & Tech Agency homepage demo (index-4.html)',
    template: 'marketing',
    tagline: 'AI & Tech Agency',
    headline: 'Intelligent products for ambitious teams',
  },
  {
    key: 'home-5',
    html: 'index-5.html',
    title: 'Orisa — Personal Creative',
    bundleSlug: 'orisa-personal-creative',
    pageSlug: 'orisa-personal-creative',
    description: 'Orisa Personal Creative homepage demo (index-5.html)',
    template: 'minimal',
    tagline: 'Personal Creative',
    headline: 'Design-led work with a human touch',
  },
  {
    key: 'home-6',
    html: 'index-6.html',
    title: 'Orisa — Branding Studio',
    bundleSlug: 'orisa-branding-studio',
    pageSlug: 'orisa-branding-studio',
    description: 'Orisa Branding Studio homepage demo (index-6.html)',
    template: 'creative',
    tagline: 'Branding Studio',
    headline: 'Bold identities for brands that want to stand out',
  },
  {
    key: 'home-7',
    html: 'index-7.html',
    title: 'Orisa — Startup Agency',
    bundleSlug: 'orisa-startup-agency',
    pageSlug: 'orisa-startup-agency',
    description: 'Orisa Startup Agency homepage demo (index-7.html)',
    template: 'marketing',
    tagline: 'Startup Agency',
    headline: 'Launch faster with strategy, design, and growth',
  },
  {
    key: 'home-8',
    html: 'index-8.html',
    title: 'Orisa — UI/UX Agency',
    bundleSlug: 'orisa-uiux-agency',
    pageSlug: 'orisa-uiux-agency',
    description: 'Orisa UI/UX Agency homepage demo (index-8.html)',
    template: 'marketing',
    tagline: 'UI/UX Agency',
    headline: 'Product experiences users love to use',
  },
  {
    key: 'home-9',
    html: 'index-9.html',
    title: 'Orisa — Modern Agency',
    bundleSlug: 'orisa-modern-agency',
    pageSlug: 'orisa-modern-agency',
    description: 'Orisa Modern Agency homepage demo (index-9.html)',
    template: 'marketing',
    tagline: 'Modern Agency',
    headline: 'Modern design for forward-thinking brands',
  },
  {
    key: 'home-10',
    html: 'index-10.html',
    title: 'Orisa — 3D Studio',
    bundleSlug: 'orisa-3d-studio',
    pageSlug: 'orisa-3d-studio',
    description: 'Orisa 3D Studio homepage demo (index-10.html)',
    template: 'creative',
    tagline: '3D Studio',
    headline: 'Immersive 3D visuals that capture attention',
  },
  {
    key: 'home-11',
    html: 'index-11.html',
    title: 'Orisa — Motion & Video Studio',
    bundleSlug: 'orisa-motion-video-studio',
    pageSlug: 'orisa-motion-video-studio',
    description: 'Orisa Motion & Video Studio homepage demo (index-11.html)',
    template: 'creative',
    tagline: 'Motion & Video Studio',
    headline: 'Cinematic motion for brands with stories to tell',
  },
  {
    key: 'home-12',
    html: 'index-12.html',
    title: 'Orisa — Minimal Portfolio',
    bundleSlug: 'orisa-minimal-portfolio',
    pageSlug: 'orisa-minimal-portfolio',
    description: 'Orisa Minimal Portfolio homepage demo (index-12.html)',
    template: 'minimal',
    tagline: 'Minimal Portfolio',
    headline: 'Selected work, simply presented',
  },
  {
    key: 'home-13',
    html: 'index-13.html',
    title: 'Orisa — Architecture Studio',
    bundleSlug: 'orisa-architecture-studio',
    pageSlug: 'orisa-architecture-studio',
    description: 'Orisa Architecture Studio homepage demo (index-13.html)',
    template: 'creative',
    tagline: 'Architecture Studio',
    headline: 'Spaces and structures with lasting impact',
  },
  {
    key: 'home-14',
    html: 'index-14.html',
    title: 'Orisa — Photography Showcase',
    bundleSlug: 'orisa-photography-showcase',
    pageSlug: 'orisa-photography-showcase',
    description: 'Orisa Photography Showcase homepage demo (index-14.html)',
    template: 'portfolio',
    tagline: 'Photography Showcase',
    headline: 'Visual stories captured with intent',
  },
  {
    key: 'home-15',
    html: 'index-15.html',
    title: 'Orisa — Agency Portfolio',
    bundleSlug: 'orisa-agency-portfolio',
    pageSlug: 'orisa-agency-portfolio',
    description: 'Orisa Agency Portfolio homepage demo (index-15.html)',
    template: 'portfolio',
    tagline: 'Agency Portfolio',
    headline: 'Work that defines our creative standard',
  },
  {
    key: 'about-2',
    html: 'about-2.html',
    title: 'Orisa — About 02',
    bundleSlug: 'orisa-about-02',
    pageSlug: 'orisa-about-2',
    description: 'Orisa About 02 inner page (about-2.html)',
    template: 'about',
    tagline: 'About Us',
    headline: 'A studio built on craft, clarity, and collaboration',
  },
  {
    key: 'about-3',
    html: 'about-3.html',
    title: 'Orisa — About 03',
    bundleSlug: 'orisa-about-03',
    pageSlug: 'orisa-about-3',
    description: 'Orisa About 03 inner page (about-3.html)',
    template: 'about',
    tagline: 'About Us',
    headline: 'Where strategy meets creative execution',
  },
  {
    key: 'contact-2',
    html: 'contact-2.html',
    title: 'Orisa — Contact 02',
    bundleSlug: 'orisa-contact-02',
    pageSlug: 'orisa-contact-2',
    description: 'Orisa Contact 02 inner page (contact-2.html)',
    template: 'contact',
    tagline: 'Contact Us',
    headline: 'Start a conversation',
  },
  {
    key: 'portfolio-cinema',
    html: 'portfolio-cinema.html',
    title: 'Orisa — Portfolio Cinema',
    bundleSlug: 'orisa-portfolio-cinema',
    pageSlug: 'orisa-portfolio-cinema',
    description: 'Orisa Portfolio Cinema horizontal showcase (portfolio-cinema.html)',
    template: 'portfolio',
    tagline: 'Portfolio',
    headline: 'Cinema-style project showcase',
  },
]

export function getGenericSeedBundles(): OrisaBundleDefinition[] {
  return ORISA_BUNDLE_REGISTRY.filter((b) => !b.dedicated)
}
